### ISSUE TITLE
Advice on mocking current_date?

### ISSUE THREAD

**Issue by AndrewLane** [EqualExperts/dbt-unit-testing#102]
Hello, I have macros that use current_date for logic and the assertions I have them are a bit of a "time bomb" test in that they will eventually start failing when a new year comes around or a certain time in the next year comes around.  Any advice on how to handle this situation?  Or is it possible to mock current_date somehow?

Example:

```
A macro that assumes a new school year starts on Sep 1st every calendar year

{% macro calculate_school_year_of_current_seniors() %}
case
    when month(current_date) >= 9
    then year(current_date) + 1
    else year(current_date)
end
{% endmacro %}

```

**Comment by daveworth** [comment]
We have created a `now()` macro that can be configured per test:

```
{#
  Use this macro instead of the database-native NOW() method to allow overriding
  the results of NOW() in unit-tests by way of the `now` configuration variable
  therein.
#}
{% macro now() %}
   {%- if 'unit-test' in config.get('tags') and config.get('now') -%}
      {{ "'" ~ config.get('now') ~ "'::timestamptz" }}
   {%- else -%}
      now()
   {%- endif -%}
{% endmacro %}
```

so in any model where we'd generally use `now()` we use `{{ now() }}` and in a test tagged `unit-test` that also has a `now='<some timestamp>'` value in the `config` block that value is returned for now.  It has worked pretty well!  We'd love to see this upstreamed if it helps others.

**Comment by AndrewLane** [comment]
Elegant solution!  Thanks!

**Comment by cdiniz** [comment]
@daveworth Thank you for the support
