### ISSUE TITLE
Support for metric tables

### ISSUE THREAD

**Issue by WillianFuks** [EqualExperts/dbt-unit-testing#104]
I was wondering if it'd be possible to add unit tests for metric tables as a new feature.

Metrics behave a bit out of the regular pattern of nodes. When we tried using it, we stumbled upon an issue saying:

    'dict object' has no attribute 'metric.<project_name>.<metric_name>'

We found that this happens because metrics depends on nodes that are available at the `graph.metrics` keys and not `graph.nodes`. When `dbt_unit_testing` [looks](https://github.com/EqualExperts/dbt-unit-testing/blob/v0.2.6/macros/utils.sql#L69) for the metric name at the wrong place it raises the issue.

A solution would be to also search at the 'metrics' key:

```python
{% macro node_by_id (node_id) %}]
{{ return (graph.nodes[node_id] if node_id in graph.nodes else graph.sources[node_id] if node_id in graph.sources else graph.metrics[node_id])}}
{% endmacro %}
```

But this still doesn't seem to solve the whole issue. Eventually when it's time for [rendering](https://github.com/EqualExperts/dbt-unit-testing/blob/v0.2.6/macros/sql_builders.sql#L88) the raw sql code it fails again because the metric node doesn't have the sql definition inside of it (it's only available at the 'nodes' definition).

As a final challenge metrics are defined in yaml files and therefore we can't supersede `ref` with `dbt_unit_testing.ref` as it [won't find the macro](https://github.com/dbt-labs/dbt-core/issues/2942). For this last issue I don't know if replacing the value of the key 'model' in the metric node would work; maybe replacing `'model': ref('table')` with `'model': dbt_unit_testing.ref('table')` will solve this problem but not sure how Jinja manipulates memory, maybe this would only apply to the local data and not to the graph definition itself.

Hopefully we can find a solution for this, testing metrics would be an interesting feature to guarantee all of its definitions are working as expected on mock data.

Thanks in advance and congrats for this great package, it has been quite useful!

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
