### ISSUE TITLE
Mocking seed referenced in call statement

### ISSUE THREAD

**Issue by gastlich** [EqualExperts/dbt-unit-testing#107]
Hello there,

First of all I wanted thank you for building this tool and making unit testing more sophisticated with DBT 🙌 

I came across an issue, which is related to mocking seeds, that are referenced by `call statement`.

I our case, one of the models, uses a macro, which invokes behind the scene the following code:

```python
{% call statement('formulas', fetch_result=True) %}
        select
            *
        from {{ ref('formulas') }}
{% endcall %}
```

I made sure that `ref` macro is coming from `dbt-unit-testing` library. 

After running `dbt test` I can see in the logs, that it tried to invoke the following query (against BQ):

```sql

        select
            *
        from `formulas`
```

and failed due to:

```shell
14:24:45.810354 [info ] [MainThread]: Completed with 1 error and 0 warnings:
14:24:45.810474 [info ] [MainThread]:
14:24:45.810591 [error] [MainThread]: Database Error in test assert_something (tests/loan_monitor/unit/assert_something.sql)
14:24:45.810701 [error] [MainThread]:   Table "formulas" must be qualified with a dataset (e.g. dataset.table).
14:24:45.810814 [info ] [MainThread]:
```

My guess would be, that the call statement is invoked before everything else and the config doesn't contain `unit-test` at the moment of invocation, the `ref` generates a wrong table reference:
https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/tests.sql#L167

```python
{% macro ref(model_name) %}
  {% if 'unit-test' in config.get('tags') %}
      {{ return (dbt_unit_testing.ref_cte_name(model_name)) }}
  {% else %}
      {{ return (builtins.ref(model_name)) }}
  {% endif %}
{% endmacro %}
```

, but I might be wrong.

Have you been aware of this issue and do you know if there are any workarounds?

Thanks in advance

**Comment by cdiniz** [comment]
Hi @gastlich, we'll try to replicate the problem with a test. thanks for the feedback.

**Comment by psousa50** [comment]
Hi @gastlich, sorry for the late, late response. 

I think I understand what's happening here but just for confirmation, could you please tell me if you mocking the 'formulas' table, using "mockRef('formulas', ..."?

**Comment by psousa50** [comment]
Hi @gastlich, thank you very much for your example. It really helped. I'm afraid we don't support this type of scenario. We can't mock statement blocks at the moment, and I believe it would be extremely hard to do so. Do you really need to use a statement block? Wouldn't it be possible to create a model that uses the ref('sample') and does the same thing? Sorry if I'm oversimplifying.

Let me know what you think.

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
