### ISSUE TITLE
Add dbt-unit-testing to dbt package Hub

### ISSUE THREAD

**Issue by will-warner** [EqualExperts/dbt-unit-testing#108]
Hey,

Could we get the dbt-unit-testing to dbt's package hub? 

Mainly for selfish reasons (our production runner cannot import from Git) but it should also help with better handling of duplicate dependencies + get more eyeballs on the package 😄 

Love the package btw

**Comment by daveworth** [comment]
I'm in strong support if the team is in support - we'd love to lean on the `package` syntax in the Package File rather than `git` refs except in cases where we pin to a ref/SHA for specific functionality.

**Comment by lkell** [comment]
Just want to chime in as well - I think it would be fantastic for this project to be added to dbt's package hub!

**Comment by cdiniz** [comment]
Hi @will-warner, we and the people who are using the package would appreciate it if you can find the time to raise the PR.

Thank you!

**Comment by will-warner** [comment]
Thanks for the nod of approval @cdiniz - PR raised.

**Comment by will-warner** [comment]
Closing out as now added to the Hub
