### ISSUE TITLE
trino support

### ISSUE THREAD

**Issue by JackWolverson** [EqualExperts/dbt-unit-testing#109]
Hi do you plan on adding trino support ?
or would it be possible to still use this with just mocking the refs/sources correctly

**Comment by kun-hackle** [comment]
Hi, I am using trino too, Seems mocking is not working correctly. (source, ref both)

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
