### ISSUE TITLE
Support for is_incremental()

### ISSUE THREAD

**Issue by khris-pearlhealth** [EqualExperts/dbt-unit-testing#110]
Hi!

I was wondering if there was a prescribed way to test incremental models. It would require some existing state of the model and I'm not sure how to do it with this package. Is that possible?

**Comment by eugene-nikolaev** [comment]
+1, I mostly need my incremental models to be tested

**Comment by cdiniz** [comment]
Duplicate from https://github.com/EqualExperts/dbt-unit-testing/issues/83
