### ISSUE TITLE
Updating dbt_utils pin?

### ISSUE THREAD

**Issue by joonas** [EqualExperts/dbt-unit-testing#112]
Hi there,

I was hoping to test out the changes from 7e9913abda0589986cccc0a54b308d80f015a79e locally in our dbt project by updating our `dbt-unit-testing` package pin to that revision, and while doing so I noticed that another package we make use of (`dbt-labs/dbt_utils`) is currently [pinned by `dbt-unit-testing`](https://github.com/EqualExperts/dbt-unit-testing/blob/7e9913abda0589986cccc0a54b308d80f015a79e/packages.yml#L2-L3) to a version that clashes with our pin (`1.0.0`).

I was reviewing the [PR that introduced this change](https://github.com/EqualExperts/dbt-unit-testing/pull/103), but wasn't able to determine as to why this needed to be made, so I thought I'd ask whether it might be possible to update this pin to allow for version `1.0.0` of `dbt_utils` or whether there's work that needs to be done in `dbt-unit-testing` in order to support it that we might be able to take on?

**Comment by daveworth** [comment]
Bump - our team would love to get in some newer changes but depend on `dbt_utils` at `1.0.0` - is there any chance this can be relaxed?

**Comment by psousa50** [comment]
Hi all, definitely, we should do this. We have been busy lately, but you'll try to do it soon. Or maybe meanwhile someone would like to create a PR for this 🙂
