### ISSUE TITLE
Support source files

### ISSUE THREAD

**Issue by tsanton** [EqualExperts/dbt-unit-testing#113]
Hi!

First of all: I'm very pleased to find this library and I'm very much looking forward to working with it!

I am wondering if you guys can consider adding `source_file` arguments to `mock_ref`, `mock_source` and `expect`?

The idea here is to clean up tests and hopefully keeping it a bit more DRY by keeping the test and assertions CSV/JSON  in separate files from the test implementations.

It could look something like this:

```
├── unit
│   ├── database
│   │   ├── some_common_data1.csv
│   │   ├── schema
│   │    │   ├── some_common_data2.csv
│   │    │   ├── some_common_data3.json
│   │    │    |    ├── table_1
│   │    │    |    |    ├── expect_data1.csv
│   │    │    |    |    ├── test_table_1.sql
```

Thinking there should be support for relative and absolute paths.

A test would look something like this:

```
{{ config(tags=['unit-test']) }}

{% call dbt_unit_testing.test('customers', 'should sum order values to calculate customer_lifetime_value') %}
  
  {% call dbt_unit_testing.mock_ref ('stg_customers', source_file="/dbt/unit/database/some_common_data1.csv") %}
  
  {% call dbt_unit_testing.mock_ref ('stg_customers', source_file="../some_common_data2.csv") %}
  
  {% call dbt_unit_testing.mock_ref ('stg_payments', source_file="../some_common_data3.csv") %}

  {% call dbt_unit_testing.expect(source_file="./expect_data1.csv") %}
{% endcall %}
```
Would love your thoughts and feedback on this; would be happy to contribute! :)

**Comment by cdiniz** [comment]
Hi @Tsanton,

Thank you for the feedback and the idea; we appreciate it!

We've considered this in the past, but we've decided to maintain the assertions in the tests to:
- Encourage people to embrace the unit test concept, testing the smallest unit of functionality in the models separately.
- Increase readability by having the assertions in the same place you have the test.

These are our main drivers for the decision.

**Comment by md17482** [comment]
Thanks for your reply @cdiniz. We have just started using dbt-unit-testing and are also very happy with the package. It's so great to be able to mock dependencies in a SQL query! However I agree with @Tsanton, in order for this package to have the widest appeal I think it would be invaluable to have the option of importing mocked data from a source file. There are cases where some of our dependencies are very large tables with many columns, and it is very tedious and inefficient to have to paste this multiple times when we use the same source for up to 20 different tests in the same test file.

**Comment by Tsanton** [comment]
Hi @md17482; this is exactly the same issue we're having -> large tables and tedious breakage of DRY. 
We're looking into forking the project as it's a must for us to simplify data handling as we're testing thousands of models.
Hope you guys will reconsider @cdiniz; we'd be happy to contribute if this will be approved :)

**Comment by darist** [comment]
Hi there!

I would add that DRY is not necessarily a desirable property of unit tests in general (see https://testing.googleblog.com/2019/12/testing-on-toilet-tests-too-dry-make.html). 

That said, I see value in what you describe and I wonder if it can be achieved with seeds. eg:

Put data in seeds:

```
seeds/some_common_data1.csv
...
```

Write tests that mock some table by using the seed
```
> tests/mytest.sql

{{ config(tags=['unit-test']) }}

{% call dbt_unit_testing.test('customers', 'should sum order values to calculate customer_lifetime_value') %}
  
  {% call dbt_unit_testing.mock_ref ('stg_customers') %}
    select * from {{ ref("some_common_data1.csv") }}
  {% endcall %}
  ...
{% endcall %}
```

Run `dbt seed` before `dbt test`

```
dbt seed
dbt test 
```

Disclaimer: I haven't actually tried this... just an idea at this point.

**Comment by Tsanton** [comment]
Hi @darist and sorry for not getting back to you sooner! :)

Though I agree with it not always being a desirable property, I think it will greatly enhance readability and speed of development^^

To get back to your seed suggestion; I believe it will be slow not running it as CTEs. Further I wonder if we'll be able to reseed tables and test it multiple ways (i.e. multiple seeds for a single table)?

@cdiniz is it possible to make a decision on this subject soon? :) We 're getting close to having to implement it one way or another -> fork is always possible but we'd love to have it as a native feature!

Speak soon!


/T

**Comment by amrithvm** [comment]
@tsanton did you go ahead and implement this? curious about your approach/decision here as we've run into a similar dilemma

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
