### ISSUE TITLE
Skip the middle table or view to get test expectations

### ISSUE THREAD

**Issue by Danny-mx** [EqualExperts/dbt-unit-testing#114]
Can we define the input on a original table and then define the test expectations on the wide table. So i can skip the middle dependency cause maybe there is so many fileds on it and i do not wanna put it in the test.
Original table ->view1->view2-> wide table

**Comment by psousa50** [comment]
Hi @Danny-mx, it should work, dbt-unit-testing use the original sql for tables/views that are not mocked. Have you tried it? And if so, could you please tell us why it didn't work? 

Thank you

**Comment by Danny-mx** [comment]
hint: 'str object' has no attribute 'information_schema'

**Comment by psousa50** [comment]
Hi Danny, is it possible for you to run your "dbt test" command with the option --vars "verbose: true" and paste here the result?

**Comment by psousa50** [comment]
Hey there, @Danny-mx! Is the issue you mentioned still persisting?  Let me know if you need any assistance or have any updates

**Comment by daveworth** [comment]
Hi @psousa50 - I think this may still exist and be related to a draft PR I opened against this repo (I was hoping for CI to tell me if I broke things).  I will attempt to get an explanatory dbt project together to demonstrate the issue I believe @Danny-mx was encountering (and so am I).

**Comment by daveworth** [comment]
Hi @psousa50 - I believe what @Danny-mx is experiencing is documented in the #144 along with an associated fix. I'd love some feedback on that change as we are currently running off of a fork with my change locally.

**Comment by psousa50** [comment]
Hi all, could you please let me know what's the status of this issue? I can't find a reason why it's not working

Thanks!
