### ISSUE TITLE
Unit test case for call statement

### ISSUE THREAD

**Issue by Naveenlbg** [EqualExperts/dbt-unit-testing#118]
Hi DBT team, 

I can writing a unit test case for dbt macros in which one of the macro has a call statement and get the result(load_result) and perform some business logic , Question : Is there any way i can mock the result of the call statement ?

`
{% macro get_max_level(src,product, default=1) -%}
{%- if not execute -%}
    {{ return(default) }}
{% endif %}
    {%- call statement('get_max_level', fetch_result=true) %}
        SELECT
            max(level) as level
        FROM
              {{ src.database }}.{{ src.schema }}.employee
        
    {%- endcall -%}
    {%- set level = load_result('get_max_level') -%}
    {%- if level and level['data'] -%}
    {%- set level_data = product_level['data'] | map(attribute=0) | list %}
    {{ return(product_level_data[0]  | as_number ) }}
    {%- else -%}
    {{ return(default | as_number ) }}
    {%- endif -%}
{%- endmacro %}

`

**Comment by psousa50** [comment]
Hi @Naveenlbg , I'm afraid we don't have this feature at the moment. Some thoughts and ideas have been given to macros unit testing so maybe we will have something about this in the future.

Thank you for your contribution and for using dbt_unit_testting 🙂
