### ISSUE TITLE
Questions about mocking strategies

### ISSUE THREAD

**Issue by mikael-ljung** [EqualExperts/dbt-unit-testing#120]
Hello,

First of all, thank you for creating this package, as it's incredibly helpful for unit-testing dbt models. I've been using the "include_missing_columns" strategy, but I'm running into some issues with Bigquery complaining about query complexity when building the entire DAG to infer missing columns.

Specifically, I'm wondering why it's necessary to build the entire DAG to infer missing columns using this strategy. Would it be possible to only look at the immediate parent nodes instead? 

Thank you in advance for your help!

**Comment by psousa50** [comment]
Hi @mikael-ljung, I'm glad that you find this package helpful 🙂  

Have you tried the option "use_database_models"? It should simplify the query used to fetch the missing columns.

Please give it a try and let us know if it helps.

**Comment by mikael-ljung** [comment]
Hi @psousa50,

Yes, I have tried that. I have a test setup that where I'm running with the options:

`{% set options = {"include_missing_columns": true} %}`

And it works just fine. However, when I'm replacing that for:

`{% set options = {"use_database_models": true} %}`

It complains that columns are missing. Is there any examples where the `use_database_models ` is used?

**Comment by psousa50** [comment]
It's a bit hard to understand the problem without more information. Could you run your "dbt test" command with the option  --vars "verbose: true" and paste here the result?

**Comment by psousa50** [comment]
Hi @mikael-ljung , are you still having this issue?

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
