### ISSUE TITLE
'except' is undefined

### ISSUE THREAD

**Issue by mahdimostafalighthouselabs** [EqualExperts/dbt-unit-testing#121]
Hello there,

I am trying to build a unit test but seem to get an error. This is my script in the test folder:

```
{{ config(tags=['unit-test']) }}

{% call dbt_unit_testing.test('intermediate_model','clocktower_tasks') %}
  {% call dbt_unit_testing.mock_ref ('raw_model') %}
     select 1 as users_id
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select  1  as users_id
  {% endcall %}

{% endcall %}
```

and this is the error I get:
```
 Compilation Error in test raw_unit_test (tests/raw_unit_test.sql)
09:15:41    'except' is undefined
09:15:41    
09:15:41    > in macro build_test_report (macros/tests.sql)
09:15:41    > called by macro test (macros/tests.sql)
09:15:41    > called by macro build_test_queries (macros/tests.sql)
```
Have I missed something out? or is the build not valid?

**Comment by psousa50** [comment]
Hi @mahdimostafalighthouselabs , could you please me which database are you using?

**Comment by alaneve** [comment]
I also ran into this. Replacing `except()` with `dbt_utils.except()` worked for me and a coworker. 

https://github.com/EqualExperts/dbt-unit-testing/blob/7594c1d79fda35b4e6ee2975f5eb55245ec3d7f3/macros/tests.sql#L87-L95

Replace above with this
```sql
    extra_entries as (
    select '+' as diff, count, {{columns}} from actual
    {{ dbt_utils.except() }}
    select '+' as diff, count, {{columns}} from expectations),

    missing_entries as (
    select '-' as diff, count, {{columns}} from expectations
    {{ dbt_utils.except() }}
    select '-' as diff, count, {{columns}} from actual)
```

**Comment by alaneve** [comment]
Looks like issue #88 was flagging the reverse of this and spawned PR #94 which removed the dbt_utils specification. 

My team is using dbt 1.0.5, and the migration of `except()` into dbt-core happened in v1.2.0 (https://github.com/dbt-labs/dbt-core/releases/tag/v1.2.0) to solve their issue 4813 https://github.com/dbt-labs/dbt-core/issues/4813, so it seems like the more recent versions of dbt-core shouldn't have this problem. 

If supporting older versions of dbt-core is off the table, I'd think dbt-unit-testing should at least identify the minimum dbt-core version required which appears to be v1.2.0.

**Comment by cdiniz** [comment]
Hi @alaneve, you're right. We should have flagged and bumped the major version. We'll update the README accordingly. 

You could use [v0.2.3](https://github.com/EqualExperts/dbt-unit-testing/releases/tag/v0.2.3) while you use older versions of dbt-core.

Thank you for the feedback.
