### ISSUE TITLE
FR: CodeGen template feature

### ISSUE THREAD

**Issue by ricky-at-domain** [EqualExperts/dbt-unit-testing#124]
Hi, just wondering if you have a plan to include something similar to CodeGen so it will look up the dependent model/seed/source and pre-generate the mock_ref template so user just focus on the mock data :)

**Comment by cdiniz** [comment]
Hi @ricky-at-domain, we don't have the plan to include it, but it's interesting to think about that. 
Thank you for the idea.

**Comment by ricky-at-domain** [comment]
hi @cdiniz, we have built the mock generation template for our internal use, this speeds up our entire unit test setup process and can have more time focus on mock data collection, just want to share the code for others as well, here our PR, https://github.com/EqualExperts/dbt-unit-testing/pull/131/files

**Comment by psousa50** [comment]
Hi @ricky-at-domain, I wanted to express our gratitude for your valuable contribution. Your code is undeniably useful, but we have some reservations about including it as part of the package. We believe it would be more beneficial for everyone if users simply copied the code to their own projects and utilized it from there.

Personally, I will definitely be following that approach, and once again, I want to sincerely thank you for your contribution. Your efforts are greatly appreciated! If you have any other ideas or suggestions, please feel free to share them. 🙂
