### ISSUE TITLE
Running against Athena

### ISSUE THREAD

**Issue by DrValani** [EqualExperts/dbt-unit-testing#128]
I have started using the unit test library against athena. Early feedback, the only thing I have had to do at the moment is override `ref` as follows: In macros created a file called `ref.sql` with: 
```sql
{% macro ref(model_name) %}
  {% if 'unit-test' in config.get('tags') %}
    {% do return(builtins.ref(model_name).include(database=false, schema=false)) %}
  {% else %}
    {% do return(builtins.ref(model_name).include()) %}
   {% endif %}

{% endmacro %}
```

Open to ideas on how best to contribute this back to the library for other users that use athena

**Comment by psousa50** [comment]
Hi @DrValani, could you please elaborate a bit more on this? Are you able to run unit tests with this macro? It seems dbt_unit_testing is not being used. In your models, are you using "ref(" or "dbt_unit_testting.ref("?
