### ISSUE TITLE
Help: expect() macro selects from actual table instead of mocking select query

### ISSUE THREAD

**Issue by mike-bolshakov** [EqualExperts/dbt-unit-testing#130]
Hi,
thank you for a truly great and super helpful module!
I am just getting my hands dirty with dbt unit testing, so might be missing or misinterpreting some concepts.
Disclaimer:  using redshift db engine.
My problem is the following:
For some reason `dbt_unit_testing.expect()` selects from the actual dwh table instead of a mock select query.
Lets say this is my model that i am trying to test (might not make sense to test it, but there is something very confusing about it)
```
select
    {{ select_star(from=api.Relation.create(database=target.database, schema="staging", identifier="session_status_proposals_v"))}},
    '{{var("tenant_name")}}' as tenant_name
from {{ ref("session_status_proposals_v") }}
{% if get_adapter_type() == 'redshift' %}
union all
select
    {{ select_star(from=api.Relation.create(database=target.database, schema="staging", identifier="session_status_proposals_us_v"))}},
    'us' as tenant_name
from {{ ref("session_status_proposals_us_v") }}
{% endif %}

```
Rather a simple union of 2 tables.

Here is my test:
```
-- depends_on: [{{ ref('session_status_proposals_v') }}, {{ ref('session_status_proposals_us_v') }} ]
{{ config(tags=['unit-test']) }}
{% set options = {"include_missing_columns": true} %}

{% call dbt_unit_testing.test('session_status_proposals_union_s', 'should verify that both tenants exist in the final table') %}
  
  {% call dbt_unit_testing.mock_ref('session_status_proposals_v') %}
        select  
        'comment_1' as comment,
        'created_at_1' as created_at,
       <rest of the table columns> 
 {% endcall %}
  
  {% call dbt_unit_testing.mock_ref('session_status_proposals_us_v') %}
    select
        'comment_1' as comment,
        'created_at_1' as created_at,
       <rest of the table columns>
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select 
       'comment_1' as comment,
        'created_at_1' as created_at,
       <rest of the table columns>

        union all

         'comment_1' as comment,
        'created_at_1' as created_at,
       <rest of the table columns>
  {% endcall %}
{% endcall %}
```
But instead of comparing 2 rows with 2 rows and outputting a success message, it does something different, so i get an error message
```
19:55:52.983432 [info ] [Thread-1  ]: ERROR: Number of Rows do not match! (Expected: 2, Actual: 442141)
19:55:52.983848 [info ] [Thread-1  ]: ERROR: Rows mismatch:
```
due to the fact that it compares 2 mock input rows with expected data which turned out to be the entire dataset of 44K rows.
I thought screenshot would make more sense to demonstrate the issue
![image](https://user-images.githubusercontent.com/112561315/229220873-ec2b25ac-d117-4bb4-8ea7-ac1316a4c3c1.png)

In my attempt to debug and understand the problem, i cloned the current repo and tried to reproduce my test using `jaffle-shop` data:
query (added `stg_calls` created with identical query as `stg_orders`)
```

select
{{ select_star(from=api.Relation.create(database=target.database, schema="s_staging", identifier="stg_orders"))}},
'eu' as tenant_name
from {{ ref('stg_orders') }}
union all
select
{{ select_star(from=api.Relation.create(database=target.database, schema="s_staging", identifier="stg_calls"))}},
'us' as tenant_name
from {{ ref('stg_calls') }}
```
using the following test:
```
-- depends_on: {{ ref('stg_calls') }}
-- depends_on: {{ ref('stg_orders') }}

{{ config(tags=['unit-test']) }}
{% set options = {"include_missing_columns": true} %}

{% call dbt_unit_testing.test('orders', 'should verify that both tenants exist in the final table') %}
  
  {% call dbt_unit_testing.mock_ref('stg_calls') %}
    select
        50 as customer_id,
        '2018-01-05 00:00:00.000' as order_date,
        54 as order_id,
        'completed' as status,
        '1' as rn
  {% endcall %}
  
  {% call dbt_unit_testing.mock_ref('stg_orders') %}
    select
        54 as customer_id,
        '2018-02-25 00:00:00.000' as order_date,
        52 as order_id,
        'return_pending' as status,
        '2' as rn
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select 
        50 as customer_id,
        '2018-01-05 00:00:00.000' as order_date,
        54 as order_id,
        'completed' as status,
        '1' as rn
        union all
        select
        54 as customer_id,
        '2018-02-25 00:00:00.000' as order_date,
        52 as order_id,
        'return_pending' as status,
        '2' as rn
  {% endcall %}
{% endcall %}
```
But doing so works properly, test pass and `expect()` selects from the mock select query
![image](https://user-images.githubusercontent.com/112561315/229223232-d4a8c783-70f8-4032-9883-43d8b3090c02.png).

In both case i used same redshift cluster, dbt 1.3.0.
Tried looking into the source code and understand the macros, but that didnt help.
Any idea what it`s not working as expected? Am i missing something?
Any hints which direction i should be looking at are much appreciated.
Thank you!
Best, Mike

**Comment by psousa50** [comment]
Hi @mike-bolshakov, it looks like you are not using "**dbt-unit-testing.ref**" in your models. If that's the case, you need to redefine the **ref** macro as explained here in the [README](https://github.com/EqualExperts/dbt-unit-testing#requirement).

Please let me know it it helps

**Comment by mike-bolshakov** [comment]
@psousa50 thank you for pointing that out, that was indeed the issue. I do not know how i missed that. 
Thank you very much!

**Comment by psousa50** [comment]
no worries, glad that you find the module useful 🙂
