### ISSUE TITLE
Clickhouse feature; getting columns from source; fix field name and table path

### ISSUE THREAD

**Issue by gladkikhtutu** [EqualExperts/dbt-unit-testing#138]
Hi! We used your package in our company for unit testing in DBT and we had some issues. 
1. Getting column names from query sometimes not work in our case, so we can need to get it from source.yaml table description. I added union of those ways.
2. For clickhouse join is not working so we need to point out join algorithm and I added it under the conditional with adapter type. I guess it is not best practice to add such cases in code, and if you don't agree with such change, can you offer something better? 
3. In different databases you have only schema and no database name in table path, so node.database can be empty and I handle this case.
4. Count is popular word and it can be a field in initial query, so we need to use more specific name

PR for these issues:
#137

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
