### ISSUE TITLE
Source not mocked with `mock_source` or `mock_ref`

### ISSUE THREAD

**Issue by joelberkeley** [EqualExperts/dbt-unit-testing#139]
I want to mock my BigQuery source. I've tried using `mock_source` according to

https://github.com/EqualExperts/dbt-unit-testing#anatomy-of-a-test

but I see an error
```
'dict object' has no attribute "source.foo.tbl.{'input_format': 'csv'}"
```

I looked in the source code and it seems `mock_source` expects two args, source and table name, so I did

```
dbt_unit_testing.mock_source('source_name', 'table_name', {'input_format': 'csv'})
```

but it's not mocking the data, it's just using the BQ data. How do I mock a BQ source?

**Comment by joelberkeley** [comment]
Note I experienced
```
13:42:36  Compilation Error in test test_foo_bar (tests/unit/test_foo_bar.sql)
13:42:36    dbt was unable to infer all dependencies for the model "test_foo_bar".
13:42:36    This typically happens when ref() is placed within a conditional block.
13:42:36    
13:42:36    To fix this, add the following hint to the top of the model "test_foo_bar":
13:42:36    
13:42:36    -- depends_on: {{ ref('stg__foo__bar') }}
```
I added that line and I'm wondering if that's breaking the mocking

**Comment by joelberkeley** [comment]
I'm actually seeing the same when I try to mock out another table (it shows that error then uses the actual BQ table when I add the suggested fix)

**Comment by joelberkeley** [comment]
I've just seen this

https://github.com/EqualExperts/dbt-unit-testing#requirement

and this

https://github.com/EqualExperts/dbt-unit-testing#known-limitations

so it appears using
```
-- depends_on: {{ ref('some_model') }}
```
is correct but still not working for me

**Comment by psousa50** [comment]
Hi @joelberkeley , are you using "dbt_unit_testing.ref" in your models? If not, you need to redefine the ref and source macros, as stated in the [README](https://github.com/EqualExperts/dbt-unit-testing/blob/master/README.md#available-macros:~:text=Alternatively%2C%20if%20you%20prefer%20to%20keep%20using%20the%20standard%20ref%20macro%20in%20the%20models%2C%20you%20can%20add%20these%20macros%20to%20your%20project%3A)

Let me know if it helps

**Comment by joelberkeley** [comment]
hi, yeah I saw that. I want to use the builtin functions so I've opted to use
```
-- depends_on: {{ ref('some_model') }}
```
as mentioned in 

https://github.com/EqualExperts/dbt-unit-testing/blob/master/README.md#known-limitations

**Comment by joelberkeley** [comment]
oh i see - that's just for using `builtins.ref` in other context, and I need to use `dbt_unit_testing.ref` generally. OK thanks. I think I'll need to look at alternative options in that case, to avoid modifying the source

**Comment by psousa50** [comment]
Hi @joelberkeley , we can use [this](https://github.com/EqualExperts/dbt-unit-testing/blob/master/README.md#available-macros:~:text=Alternatively%2C%20if%20you%20prefer%20to%20keep%20using%20the%20standard%20ref%20macro%20in%20the%20models%2C%20you%20can%20add%20these%20macros%20to%20your%20project%3A) approach if you don' want to modify the source

**Comment by GavinChowUp** [comment]
Hi @psousa50, I followed the advice, and still can't mock data and directly use database data,  did I missed sth?  my steps are: 
- redefine the `ref`, and `source` macros in the file: `redifined_ref_source.sql`.
```sql
{% macro ref(model_name) %}
   {{ return(dbt_unit_testing.ref(model_name)) }}
{% endmacro %}
{% macro source(source, model_name) %}
   {{ return(dbt_unit_testing.source(source, model_name)) }}
{% endmacro %}
```
- in my `intermediate` layer  model:`combine_category_and_project.sql`. The way I use  remains :
```sql
with

    project as (select * from {{ ref("project") }}),

    catagory as (
        select project_id, category
        from {{ ref("catagory_source1") }}
        union
        select project_id, category
        from {{ ref("catagory_source2") }}
    ),

    result as (
        select project.*, catagory.category
        from project
        left join
            catagory
            on project.id = catagory.project_id
    )
select *
from result

```
- then  I want to use mock data and test the logic of:`combine_category_and_project.sql` in `test_combine_category_and_project`, the way I use is : 
```sql

-- depends_on: {{ ref('project') }}
-- depends_on: {{ ref('catagory_source1') }}
-- depends_on: {{ ref('catagory_source2') }}

{{ config(tags=['tag1']) }}

{% call dbt_unit_testing.test('combine_category_and_project', 'should map category') %}

    {% call dbt_unit_testing.mock_ref('project', {"input_format": "csv"}) %}
        id,name,display_name
        13,'aa','bb'
        18,'cc','dd'
    {% endcall %}

    {% call dbt_unit_testing.mock_ref('catagory_source1', {"input_format": "csv"}) %}
        project_id, category
        13,'category1'
    {% endcall %}

    {% call dbt_unit_testing.mock_ref('catagory_source2', {"input_format": "csv"}) %}
        project_id, category
        18,'category2'
    {% endcall %}

    {% call dbt_unit_testing.expect({"input_format": "csv"}) %}
        id,name,display_name,category
        13,'aa','bb','category1'
        18,'cc','dd','category2'
    {% endcall %}

{% endcall %}

```
