### ISSUE TITLE
Is there a way not to connect the DB when Unit testing?

### ISSUE THREAD

**Issue by GavinChowUp** [EqualExperts/dbt-unit-testing#148]
Hi team, Thanks for providing this awesome framework to make SQL unit testing a reality, I want to unit test SQL, but I have to connect to the database, I see that the framework also has a way to mock data,  but still need to connect to the database to run this command:

 **dbt test --select [tests/unit/tests.sql](https://github.com/EqualExperts/dbt-unit-testing/blob/699fd6a6140d1cb5ccdd65280ca6f3380384f253/jaffle-shop/tests/unit/tests.sql)**

This invisible adds a layer of dependency, am I missing something?

**Comment by psousa50** [comment]
Hi @GavinChowUp, I'm afraid that's something we can't control. The `dbt test` command requires the database to be running. However, the framework is designed to work without any models or sources in the database. You just need to mock the models used by the model you want to test, and that should be enough.

Let me know if this answers your question or if you need something else.

Thank you!

**Comment by GavinChowUp** [comment]
Thank you @psousa50, The clear answer solved my confusion as a beginner
