### ISSUE TITLE
Support for ephemeral models

### ISSUE THREAD

**Issue by amrithvm** [EqualExperts/dbt-unit-testing#149]
Hi! is there any support planned/natively available for testing ephemeral models? as they essentially represent CTEs rather than being built directly into the database (can't run operations, etc. on them), are they testable at all via dbt-unit-testing? considering writing a python module around this but was curious.

**Comment by psousa50** [comment]
Are you still having this issue? `dbt-unit-testing` does support ephemeral models. Please let us know what difficulties you are having and we will try to help you out.

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
