### ISSUE TITLE
Add tags to repo / host on dbt hub

### ISSUE THREAD

**Issue by louis-vines** [EqualExperts/dbt-unit-testing#15]
Hi All 👋 

I came across your blog post / repo a few weeks back and have been chiming in to various slack threads / github discussions in support of the features that this package is trying to provide. It's clearly the best attempt at proper unit testing in the dbt space right now.

I'm actually wanting to use this package in anger and would be keen to get involved with maintaining it too. I've already come across a few issues...

Firstly are you intending this repo to be consumed publicly? If so have you thought about hosting on dbt hub? Failing that could you tag some of the releases so it's possible to pin the version of the code when you install it via dbt?

Currently, dbt rightly gives you this warning when you install:

```
15:32:46  WARNING: The git package "https://github.com/EqualExperts/dbt-unit-testing"
	is pinned to the "master" branch.
	This can introduce breaking changes into your project without warning!

See https://docs.getdbt.com/docs/package-management#section-specifying-package-versions
15:32:46  Installing dbt-labs/dbt_utils
```

**Comment by psousa50** [comment]
Couldn't agree more with you @louis-vines, and thank you for your feedback. We are still in an early stage of development but as soon as we have a more stable version we'll do what you suggested.

**Comment by louis-vines** [comment]
Great - I'm keen to be a contributor to this project too 👍

**Comment by tnightengale** [comment]
@psousa50 would it be possible to simply tag a `0.0.1` alpha release? This would at least allow folks to pin to something other than the `master` branch using the dbt git package syntax, eg:
```
packages:
   - git: "https://github.com/EqualExperts/dbt-unit-testing.git"
    revision: 0.0.1
```

**Comment by cdiniz** [comment]
We've tagged the first version:

```
packages:
  - git: "https://github.com/EqualExperts/dbt-unit-testing"
    revision: v0.1.0
```
