### ISSUE TITLE
Hard to see 'space' diffs in the test feedback

### ISSUE THREAD

**Issue by franzoni315** [EqualExperts/dbt-unit-testing#150]
I am using this dbt-unit-testing package for testing the quality of a text cleaning procedure. However, it is pretty hard to detect the reason of a failed test when the difference is just a space in the end of the string. It would be awesome, if the difference in spaces could be rendered as a red rectangle or something like this.

**Comment by psousa50** [comment]
Hi @franzoni315, thank you for your feedback. It's a good idea, something to consider in future releases 👍

**Comment by psousa50** [comment]
Please take a look at the latest release ([0.4.0](https://github.com/EqualExperts/dbt-unit-testing/releases/tag/v0.4.0)) and check if it fixes this issue.

Thank you!
