### ISSUE TITLE
Running a macro not within a model (e.g. using dbt run-operation) will fail because macros have no "tags"

### ISSUE THREAD

**Issue by wircho** [EqualExperts/dbt-unit-testing#151]
# Overview

We have a project where we sometimes run `dbt run-operation some_macro` and the `some_macro` being run uses `ref` somewhere inside it. This ends up calling `dbt_unit_testing`'s `running_unit_test()`, which checks for tags in the `config`.

This is fine when `config` is _a model_'s config. But it does not work when no model is being compiled, because in the latter scenario, `config` has no "tags" at all.

# How to reproduce

In a project set up with `dbt_unit_testing` run:

```bash
> dbt run-operation ref --args "model_name: any_existing_model"
...
  argument of type 'NoneType' is not iterable
...
```

# Suggestion 1

My recommendation is to edit this macro:
https://github.com/EqualExperts/dbt-unit-testing/blob/3bfdb45b516ebc393e43edc027ab51cb9fe5530a/macros/tests.sql#L179-L181

to this:
```jinja
{% macro running_unit_test() %}
  {{ return (config.model.resource_type.value == 'model' and 'unit-test' in config.get('tags')) }}
{% endmacro %}
```

# Suggestion 2

A simpler (and arguably safer) solution is:
```jinja
{% macro running_unit_test() %}
  {{ return (config.get('tags') and 'unit-test' in config.get('tags')) }}
{% endmacro %}
```

**Comment by malish8632** [comment]
Hello @psousa50 this fix was overwritten in the same tag 0.2.9 - the one you produced for us after this merge.
This is huge problem for us and it seems we will need to abandon this library as the handling of releases is unreliable.

https://github.com/EqualExperts/dbt-unit-testing/pull/152/files
