### ISSUE TITLE
Can't see the right model name in the test result

### ISSUE THREAD

**Issue by WeihaoLiTW** [EqualExperts/dbt-unit-testing#154]
Hi, can someone guide me on how to fix this?

There is an incorrect model name in the printed result:
![image](https://github.com/EqualExperts/dbt-unit-testing/assets/39988920/6f27907d-1ec1-4fc8-806f-24ce37aa2613)

Here is my setting:

```
{{ config(tags=['unit-test']) }}

{% set options = {"include_missing_columns": true,
                  "use_database_models": true,
                  "input_format": "csv"
                  } 
  %}

{% call dbt_unit_testing.test(model_name='int_campaign_submission_step_submit_change_history', 
                              test_description='should get right result'
                              )
  %}
  
  {% call dbt_unit_testing.mock_ref(model_name='stg_pd_campaigns_historicalsubmission_steps', options=options) %}
    ....
  {% endcall %}

  {% call dbt_unit_testing.expect(options={"input_format": "csv"}) %}
  ....
  {% endcall %}
  
{% endcall %}
```

Please let me know if anything else can help figure it out.
Thanks!!

**Comment by psousa50** [comment]
Hi @WeihaoLiTW, I believe this was fixed in v0.2.7, could you please check which version are you using?

**Comment by WeihaoLiTW** [comment]
ohh!! I used v0.2.6, just upgrade to v0.2.7, and it works! 
Thank you very much!

**Comment by psousa50** [comment]
you're welcome, glad I could help 🙂
