### ISSUE TITLE
The redefined macro ref and source not works

### ISSUE THREAD

**Issue by GavinChowUp** [EqualExperts/dbt-unit-testing#155]
Hi team, I followed the [advice](https://github.com/EqualExperts/dbt-unit-testing#requirement), and still can't mock data and directly use database data,  did I missed sth?  my steps are: 
- redefine the `ref`, and `source` macros in the file: `redifined_ref_source.sql`.
```sql
{% macro ref(model_name) %}
   {{ return(dbt_unit_testing.ref(model_name)) }}
{% endmacro %}
{% macro source(source, model_name) %}
   {{ return(dbt_unit_testing.source(source, model_name)) }}
{% endmacro %}
```
- in my `intermediate` layer  model:`combine_category_and_project.sql`. The way I use  remains :
```sql
with

    project as (select * from {{ ref("project") }}),

    catagory as (
        select project_id, category
        from {{ ref("catagory_source1") }}
        union
        select project_id, category
        from {{ ref("catagory_source2") }}
    ),

    result as (
        select project.*, catagory.category
        from project
        left join
            catagory
            on project.id = catagory.project_id
    )
select *
from result

```
- then  I want to use mock data and test the logic of:`combine_category_and_project.sql` in `test_combine_category_and_project`, the way I use is : 
```sql

-- depends_on: {{ ref('project') }}
-- depends_on: {{ ref('catagory_source1') }}
-- depends_on: {{ ref('catagory_source2') }}

{{ config(tags=['tag1']) }}

{% call dbt_unit_testing.test('combine_category_and_project', 'should map category') %}

    {% call dbt_unit_testing.mock_ref('project', {"input_format": "csv"}) %}
        id,name,display_name
        13,'aa','bb'
        18,'cc','dd'
    {% endcall %}

    {% call dbt_unit_testing.mock_ref('catagory_source1', {"input_format": "csv"}) %}
        project_id, category
        13,'category1'
    {% endcall %}

    {% call dbt_unit_testing.mock_ref('catagory_source2', {"input_format": "csv"}) %}
        project_id, category
        18,'category2'
    {% endcall %}

    {% call dbt_unit_testing.expect({"input_format": "csv"}) %}
        id,name,display_name,category
        13,'aa','bb','category1'
        18,'cc','dd','category2'
    {% endcall %}

{% endcall %}

```

**Comment by GavinChowUp** [comment]
If I remove the:
```SQL
-- depends_on: {{ ref('project') }}
-- depends_on: {{ ref('catagory_source1') }}
-- depends_on: {{ ref('catagory_source2') }}
```
It will raise the compile error:`To fix this, add the following hint to the top of the model`

actually, I have mocked all of the depends in the file:`test_combine_category_and_project .sql`

what is the root cause of this?

**Comment by psousa50** [comment]
Hi @GavinChowUp, it looks like you're missing the tag 'unit-test' in your test, as explained in the [README](https://github.com/EqualExperts/dbt-unit-testing/blob/master/README.md#:~:text=The%20first%20line%20is%20boilerplate%20we%20can%27t%20avoid%3A).

Please let me know if this fixes your issue.

Thank you

**Comment by GavinChowUp** [comment]
Hi @psousa50 Thank you very much, I did not succeed in my mock because the `unit-test` was missed, thanks for providing such a useful framework. now the mock works.
