### ISSUE TITLE
Incremental model mocking fails with include_missing_columns set to true

### ISSUE THREAD

**Issue by strictness** [EqualExperts/dbt-unit-testing#156]
We're running into problems when we try to mock our incremental models and have the include_missing_columns flag set to true. We get an "Object does not exist or not authorized error" (Snowflake).

It seems that when this flag is enabled the sql builder macro omits the {{ this }} reference, and does not mock the initial state of the incremental model.

This issue can be replicated with your own incremental model example in the README and enabling the above option.

**Comment by psousa50** [comment]
Hi @strictness, could you please tell me which version are you using? I believe this happens in v0.2.8 but it's fixed in v0.2.9. Can you verify this?

Thank you!

**Comment by strictness** [comment]
Hi @psousa50, we are using v0.2.9.

**Comment by strictness** [comment]
Hi @psousa50 ,

It's never too late :) Yes, the inital issue was resolved.

However, we do get `001042 (XX000): SQL compilation error: Compilation memory exhausted.` now since (I'm guessing) our models are rather complex.
