### ISSUE TITLE
How to unit test macros?

### ISSUE THREAD

**Issue by gaj995** [EqualExperts/dbt-unit-testing#157]
Is there a best practice on testing macros? Do you have to have a model sql file or could you directly test what's in the macro folder in test sql file? 

Any examples you can point to would be appreciated. 

Thanks

**Comment by DrValani** [comment]
So, I tend to reply on the testing functionality from dbt rather than the unit test library. See the example below. Note dbt test will fail if they get back a result hence the `actual != expected`. Also I added the tag  unit-test to make it run with my other unit tests

```
{{
    config(
        tags=['unit-test']
    )
}}

with input as (
  select
    '{{ my_macro("my_params") }}' as actual
),
expectations as (
  select actual
  from input
  where actual != 'expected output'
)

select * from expectations 
```

**Comment by psousa50** [comment]
Hi @gaj995 , we currently don't have plans to support tests for macros. You can use @DrValani suggestion 🙂
