### ISSUE TITLE
Support rounding in comparisons

### ISSUE THREAD

**Issue by gnilrets** [EqualExperts/dbt-unit-testing#159]
I've got a test failing that looks like this:

```
23:46:10  | DIFF | COUNT | PACKAGE_SK |        BIN_START_AT |                EAF |
23:46:10  | ---- | ----- | ---------- | ------------------- | ------------------ |
23:46:10  | +    |     1 | p1         | 2023-01-01 04:00:00 | 0.6000000000000001 |
23:46:10  | -    |     1 | p1         | 2023-01-01 04:00:00 |                0.6 |
```

The actual record has that ...0001 there due to floating point precision issues.  It's ugly to have such a wide column in the test (and it's possible a result like this may be inconsistent depending on the order things are added up).  I'd love to be able to specify that some fuzzyness in floating point comparisons is allowed.

**Comment by psousa50** [comment]
Please take a look at the latest release ([0.4.0](https://github.com/EqualExperts/dbt-unit-testing/releases/tag/v0.4.0)) and check if it fixes this issue.

Thank you!
