### ISSUE TITLE
source/ref macros just return text and not source/ref objects

### ISSUE THREAD

**Issue by louis-vines** [EqualExperts/dbt-unit-testing#16]
Your source/ref macros currently return the results of calling underlying source/ref object as text and this means they don't play nicely with downstream macros if you override the default source/ref macros for a project. This causes problems with e.g. the `dbt_utils.star` macro and stops my project from compiling. I'm aware the `unit-test` tagged version of this macro will probably never play nicely with `dbt_utils.star` but we could at least fix the whole project compilation with a little tweak:

Here:
https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/tests.sql#L21

we have
```
{{builtins.ref(name)}}
```
as the way the function returns.

This returns the actual text value, not the ref object and as such I get this error when using with my project:
```
Macro star expected a Relation but received the value: <example>.<schema>.<table>
```
This can be fixed by making the referenced code
```
{% do return builtins.ref(name) %}
```

I'd be keen to contribute to this project so happy to put a PR in if that's appropriate...

**Comment by cdiniz** [comment]
Hi @louis-vines. 
Thank you for your feedback.
We really appreciate it if you could contribute with a PR, we are keen to have people collaborating with us.

**Comment by louis-vines** [comment]
@cdiniz I have a PR ready but don't have permissions to open a PR in the repo. Could you change the permissions on the repo to allow PRs or make me a contributor?

**Comment by louis-vines** [comment]
I was about to put a forked PR in for this but it seems to be fixed now anyway:

```
{% macro ref(model_name) %}
{%- if 'unit-test' in config.get('tags') -%}
    {{model_name}}
{%- else -%}
    {{ return (builtins.ref(model_name)) }}
{%- endif -%}
{% endmacro %}
```

**Comment by psousa50** [comment]
HI @louis-vines, yes, I have included your suggestion in the last PR. Sorry about that, I should have told you. And thanks again for that
