### ISSUE TITLE
Support for dbt versions

### ISSUE THREAD

**Issue by philribbens** [EqualExperts/dbt-unit-testing#160]
It doesn't appear to be possible to use both [dbt versions](https://docs.getdbt.com/docs/collaborate/govern/model-versions) and dbt-unit-testing currently because [dbt-unit-testing's overridden version of ref()](https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/overrides.sql#L1-L7) doesn't accept the `version` argument like dbt's default version of `ref()` does.

**Comment by philribbens** [comment]
Others have run into this issue as well: https://getdbt.slack.com/archives/C01UM2N7814/p1690385895229359?thread_ts=1690294144.177669&cid=C01UM2N7814.

**Comment by psousa50** [comment]
Hi folks, please check v0.3.2, it includes support for model versions.

Any feedback will be most appreciated 🙂 

Thank you!

**Comment by philribbens** [comment]
Yeah it appears to be working for us now. We upgraded to v0.3.2 and were able to use dbt versions. Thank you so much!
