### ISSUE TITLE
How to gracefully resolve the Redshift Optimizer bug?

### ISSUE THREAD

**Issue by GavinChowUp** [EqualExperts/dbt-unit-testing#161]
Hi team,

   Thanks for providing such a good testing framework.

I encountered an issue while using Redshift as my data warehouse and attempting to use input CSV files as mock data for unit testing. The error message states: `"failed to find conversion function from 'unknown' to text/character varying."` After investigating, it appears that this problem may caused by a [Redshift optimizer bug.](https://getdbt.slack.com/archives/CJARVS0RY/p1582556218000200?thread_ts=1582155436.119200&cid=CJARVS0RY)

To work around this issue, I currently need to make the following adjustments:
```sql
        sk,name,wname,is_expire
        cast ('user_sk_01_true' as text),cast ('user_name_01' as text),cast('wname_01' as text),true
        cast ('user_sk_01_false' as text),cast ('user_name_01' as text),cast('wname_01' as text),false
```

However, I would prefer a more graceful solution that allows me to keep the original format, such as `'user_sk_01'`, without the need to explicitly cast the mock data like `cast('user_sk' as text)`.

If have encountered a similar issue or have insights on how to handle this gracefully? appreciate

**Comment by psousa50** [comment]
Hi @GavinChowUp , sorry for the late response.

Did you try:

```
        sk::text, name::text, wname::text, is_expire
        'user_sk_01_true', 'user_name_01', 'wname_01', true
        'user_sk_01_false', 'user_name_01', 'wname_01', false
```

Please lmk if it works for you.

Thank you!
