### ISSUE TITLE
Unit tests should not run when running dbt compile

### ISSUE THREAD

**Issue by DrValani** [EqualExperts/dbt-unit-testing#163]
Unit tests are executed when running `dbt compile`.

Is this intentional, if so why? If not, is it possible to stop tests running on compile please?

**Comment by psousa50** [comment]
Hi @DrValani .

I might be mistaken, but I believe that `dbt compile` does not execute the tests; it only compiles them. Could you please explain the issue you're experiencing so that I can attempt to assist you?

**Comment by DrValani** [comment]
Thanks for the super speedy response Pedro.

To reproduce, I change a test expectation value so that it fails. Then run dbt compile and I see the failing test output. 

This indicates that the tests are being run during compile. 

dbt-athena-community==1.5.1
dbt-unit-testing v.0.2.7


Please let me know if you need any further information.


Regards

Yogi

**Comment by psousa50** [comment]
Oh, I see what you mean. I believe the tests are not running; rather, the code is being compiled, which also involves the Jinja code responsible for sending the test report to the console. We are aware of this issue and are working on a solution. Please stay tuned for our next release. In the meantime, you might consider attempting to exclude the tests from the compile command using the --exclude option, though I'm uncertain if that is feasible in your case.

We appreciate your feedback! 👍

**Comment by wircho** [comment]
> I believe the tests are not running; rather, the code is being compiled
This does not seem to be right. In fact I can not only see tests fail during compilation, but also I see the test jobs "with expectations as etc etc" running on the BigQuery console just by running `dbt compile`

**Comment by wircho** [comment]
To add to this, the compiled `target/` code of our unit test files ends up looking like this:

```sql
select 1 as a from (select 1) as t where False
```

Which suggests that **by design** testing is actually happening at dbt compilation time, and by the end of compilation, we get either a success or a failure one-liner as the compiled SQL.

**Comment by JackWolverson** [comment]
to further add. we get an error when running dbt docs generate from the unit testing suggesting that it is running outside a dbt run (  we use a different target for unit tests due to where they run so is expected)

**Comment by amrithvm** [comment]
any update on this? we're running into this issue as well. on our end (unsure if this is common behavior), tests that are failing on dbt compile runs won't error out (i.e. the failure will still be reported, but the command will complete successfully).

**Comment by H-Max** [comment]
Hello,

same issue here with the `dbt docs generate` running unit-test, unless I add the `--no-compile` argument (which I don't want to add because I want the docs generation to compile my models).

**Comment by H-Max** [comment]
Quick followup, I found a solution to ignore unit-tests by default when running dbt. This means you have to explicitely ask for running unit test using the selector.

How ?

Simply create a `selectors.yml` file in your dbt folder:

```yaml
selectors:
  - name: default
    description: |
      Default selector when running any dbt command.
      Everything but unit-tests"
    default: true
    definition:
      union:
        - method: fqn
          value: "*"
        - exclude:
            - method: tag
              value: unit-test
```

From now on, this selector will be used unless you specify a selector yourself at runtime.
