### ISSUE TITLE
Show how to run tests in the README

### ISSUE THREAD

**Issue by benjamin-allevius** [EqualExperts/dbt-unit-testing#177]
The readme seems to be missing a pretty obvious thing: how to actually run the unit tests. From what I could figure out myself, it's something like `dbt test --model name_of_my_test_file`, but I don't know what other options exist.

**Comment by dearLilian** [comment]
I think this one should work:

dbt test --models tag:unit-test

But be sure to add `unit-test`tag to your test model.

**Comment by benjamin-allevius** [comment]
Thanks—I raised this issue more for the purpose of "this is something you should include in the README".

**Comment by psousa50** [comment]
Definitely, will do 🙂

**Comment by psousa50** [comment]
Done
