### ISSUE TITLE
Does this package work with Microsoft Synapse datawarehouse?

### ISSUE THREAD

**Issue by Rutvijjs** [EqualExperts/dbt-unit-testing#178]
I'm wondering if dbt-unit-testing works with synapse. I've tried to write very simple tests that do work with postgres however the same test wont work in synapse and gives me the following error:
` ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Parse error at line: 11, column: 7: Incorrect syntax near 'with'. (103010) (SQLExecDirectW)")`

**Comment by psousa50** [comment]
Hi @Rutvijjs , currently we don't support Microsoft Synapse. This doesn't mean that it won't work, but we don't have any tests for it.
If you run your test with `--vars "verbose: true` and paste here the output, we can take a look.
