### ISSUE TITLE
invalid Recursive CTE

### ISSUE THREAD

**Issue by louis-vines** [EqualExperts/dbt-unit-testing#18]
Me again - I'm trying to run the latest version of this project and I'm getting:

```
Runtime Error
  Database Error in test test_example (tests/models/dw/test_example.sql)
    001100 (42601): SQL compilation error:
    'CONTRACTS' is an invalid Recursive CTE
```

My model file is (`models/dw/example.sql`):

```
{{
    config(
        materialization='table',
    )
}}

with foo as (
    select
        id
    from {{ ref('contracts') }}
)

select *
from foo
```

and the test file is (`tests/dw/test_example.sql`):

```
{{
    config(tags='unit-test')
}}

{% call dbt_unit_testing.test('example', 'test 1') %}
    {% call dbt_unit_testing.mock_ref('contracts') %}
        contract_id
         1
    {% endcall %}

    {% call dbt_unit_testing.expect() %}
        contract_id
         1
    {% endcall %}
{% endcall %}

```

**Comment by psousa50** [comment]
Yup, that doesn't look right, I will test it with your example

**Comment by psousa50** [comment]
Can you also share the **contracts** model? Which database are you using?

**Comment by DrValani** [comment]
To be able to unit test recursive functions with CTEs, we would need to update the test macro to include the recursive keyword:
https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/tests.sql#L107

Note: This is for BigQuery at least, see https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#recursive_keyword

I am not sure if this applies to other databases.

**Comment by cdiniz** [comment]
I'm closing the issue due to inactivity, but we're happy to reopen.

**Comment by louis-vines** [comment]
Apologies I got dragged into a load of other things over the last few weeks so haven't had a chance to reply to this.

I think your codebase has probably moved on quite a bit since this was an issue so not sure if it is still applicable.

I have come across the same issue since when I've had CTEs with the same name as the filename they are created in but when I can't ellicit the behaviour in an isolated example so can't really share.

If I do manage to get this behaviour with an isolated example I will raise a new issue.
