### ISSUE TITLE
docs: update README to make it explicit that UNION ALL should be used between tests

### ISSUE THREAD

**Issue by NicolasGuary** [EqualExperts/dbt-unit-testing#191]
After checking the examples you provided in the repository, I noticed that `UNION ALL` statements should be used between tests in the same file. It's not really explicit and I think it could be a great addition in the README with something like : 

### Creating multiple tests in the same file

When creating multiple tests in the same test file, you need to make sure they are all separated by an `UNION ALL` statement: 

```
{{ config(tags=['unit-test']) }}

{% call dbt_unit_testing.test ('[Model to Test]','[Test Name]') %}
  {% call dbt_unit_testing.mock_ref ('[model name]') %}
     select ...
  {% endcall %}

  {% call dbt_unit_testing.mock_source('[source name]') %}
    select ...
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select  ...
  {% endcall %}

{% endcall %}

UNION ALL

{% call dbt_unit_testing.test ('[Model to Test]','[Another Test]') %}
  {% call dbt_unit_testing.mock_ref ('[model name]') %}
     select ...
  {% endcall %}

  {% call dbt_unit_testing.mock_source('[source name]') %}
    select ...
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select  ...
  {% endcall %}

{% endcall %}
```

**Comment by psousa50** [comment]
That would be a good enhancement, thank you @NicolasGuary. Would you like to submit a pull request with this? We can also do it if you don't have the time

**Comment by NicolasGuary** [comment]
Opened https://github.com/EqualExperts/dbt-unit-testing/pull/192
