### ISSUE TITLE
Proposal for Enhanced Input Handling: Utilizing External CSV Files

### ISSUE THREAD

**Issue by Idank96** [EqualExperts/dbt-unit-testing#203]
In the current workflow, examples of tables are manually created within the ".mock_ref" or ".mock_source" blocks. 
I am proposing external CSV files as an alternative input method. 
Instead of directly defining tables in these blocks, users could create CSV files containing the required data. Subsequently, the SQL component could be configured to read data from these CSV files.

By utilizing CSV files, users can conveniently manage and update their data externally, and the SQL queries can dynamically fetch information from these files during execution.

If that is not possible, is there another dbt package that can accomplish this?

Thanks

**Comment by psousa50** [comment]
Hi @Idank96,

Thanks for the suggestion but right now, we're not planning to add this feature. We think it's best to keep each test's data small and close to the test, so we won't need CSV files.

**Comment by Idank96** [comment]
Thanks @psousa50

**Comment by Siete-F** [comment]
Separating test data is still quite straightforward, but you will need to do it in macro's.
(You can create a new folder for it if you like and add it to the `macro-paths` variable in the `dbt_project.yml`)
Write your test like this:
```
{% call dbt_unit_testing.test('model_to_test') %}

  {% call dbt_unit_testing.mock_ref ('dependency_model')%}
    {{ mock_input_data() }}
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    {{ expected_result() }}
  {% endcall %}

{% endcall %}
```
And write the macro's, optionally in one file if you prefer, like so:
```
{% macro mock_input_data() %}

select 'abc0' as test_execution_id, "2024-10-10T11:12:10" as run_started_at
 union all
select 'abc1' as test_execution_id, "2024-10-10T11:12:13" as run_started_at
 union all
select 'abc2' as test_execution_id, "2024-10-10T11:12:13" as run_started_at
 union all
select 'abc3' as test_execution_id, null as run_started_at

{% endmacro %}

{% macro expected_result() %}
{# In my case, it adds a few columns to the left, therefore I made it dependend on the input macro. #}

select new.my_new_column, input.* FROM (
    select "val_1" as my_new_column, 'abc0' as test_execution_id
     union all
    select "val_1" as my_new_column, 'abc1' as test_execution_id
     union all
    select "val_1" as my_new_column, 'abc2' as test_execution_id
) as new
INNER JOIN (
    {{ mock_input_data() }}
) as input
    ON new.test_execution_id = input.test_execution_id

{% endmacro %}
```
