### ISSUE TITLE
Tests are broken for Databricks Adapter

### ISSUE THREAD

**Issue by man40** [EqualExperts/dbt-unit-testing#209]
Databricks uses backtick for identifier quote.

**Comment by man40** [comment]
Add a macro [here](https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/utils.sql#L209):
```
{% macro databricks__quote_identifier(identifier) %}
    {% if identifier.startswith('`') %}
      {{ return(identifier) }}
    {% else %}
      {{ return('`' ~ identifier ~ '`') }}
    {% endif %}
{% endmacro %}
```

**Comment by cdiniz** [comment]
@man40 We opened a PR with this. thanks! we don't support Databricks officially and we don't have the infrastructure ready to test it. If you can feedback on your databricks experience would be great to understand what we need to do in future if we decide to officially support it. thanks
