### ISSUE TITLE
Add Support for Snapshot Nodes

### ISSUE THREAD

**Issue by tnightengale** [EqualExperts/dbt-unit-testing#23]
Opening for visibility, but it seems like any upstream snapshot nodes are failing to be rendered.

**Comment by cdiniz** [comment]
Hi @tnightengale, Thank you for your feedback. 
We're trying to understand how can we add the snapshot support into the unit test package.
We'll share our progress when we have something in place.

**Comment by cdiniz** [comment]
https://github.com/EqualExperts/dbt-unit-testing/pull/50

**Comment by cdiniz** [comment]
Solved by #50
