### ISSUE TITLE
Hi, do you have a plan for Redshift?

### ISSUE THREAD

**Issue by kienvht** [EqualExperts/dbt-unit-testing#74]
Hi, I'd like this project. But I can't see Redshift in Compatibility. Do you have a plan for Redshift? Thank you

**Comment by cdiniz** [comment]
Hi @kienvht, we don't have an exact plan; we're working towards feedback. Since there is interest in using redshift, we'll work on it. Since we're compatible with Postgres, It should not require many changes; it's just a matter of setting up the infrastructure so we can test it in our CI. Have you tried it against Redshift, by any chance?

Thank you for your interest!

**Comment by toddy86** [comment]
@cdiniz I just stumbled across your package in my search for better ways to unit test dbt. Love the project and from a glance, it looks like you have done a good job of wrangling dbt into a good looking framework!

We use redshift, so I can test out the package and see what does / doesn't work. But do you have any initial ideas on what may or may not work? Or is it literally just that you do not have this setup on your CI?

If you point me in the right direction of what / where changes may need to be made, I might be able to look into adding support for Redshift as part of my evaluation. 

Cheers

**Comment by cdiniz** [comment]
Hi @toddy86. 

We didn't have the time to add Redshift in our CI, to test it out. Although, since Redshift is based on postgres, I guess it should work.

Could you please give us feedback about your testing? thanks

Thanks for the feedback.

**Comment by toddy86** [comment]
Redshift is indeed historically based off Postgres, however it is very much a different beast these days. Their fork was from many moons ago. 

Will let you know how I get on when I get around to trialling it out. Cheers

**Comment by jmasonlee** [comment]
I would like to know this too!
I'm also interested in a redshift integration.

**Comment by cbeiro** [comment]
Hi! I'm trying to test this out with Redshift and I'm getting an error when defining a source,   'dict object' has no attribute 'source.name_of_the_source'. Could this be caused by the integration not being ready or I could be configuring something wrong? Thanks!

**Comment by cbeiro** [comment]
The issue was a configuration problem and not related to Redshift. I was able to run all tests successfully.
