### ISSUE TITLE
dbt was unable to infer all dependencies for the model

### ISSUE THREAD

**Issue by amirse** [EqualExperts/dbt-unit-testing#75]
Hey there.
Trying this out, I wrote a simple test that looks like this:
```
{{ config(
          tags=['unit-test']
   ) 
}}




{% call dbt_unit_testing.test('yankees_catchers', 'Test catchers query') %}

  {% call dbt_unit_testing.mock_ref ('yankees') %}
    select 'bobby' as name,
     'NYY' as team,
     'Catcher' as position,
     cast ('24' as int4) as height,
     cast ('239' as int4) as weight,
     cast ('23' as int) as age
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select 'bobby' as name,
     'NYY' as team,
     'Catcher' as position,
     cast ('24' as int4) as height,
     cast ('239' as int4) as weight,
     cast ('23' as int) as age
  {% endcall %}
{% endcall %}
```
As seen, it relies on the yankees model, which I try to mock. But when I run the test I get
```
16:29:39    dbt was unable to infer all dependencies for the model "mlb_test".
16:29:39    This typically happens when ref() is placed within a conditional block.
16:29:39    
16:29:39    To fix this, add the following hint to the top of the model "mlb_test":
16:29:39    
16:29:39    -- depends_on: {{ ref('yankees') }}
16:29:39    
16:29:39    > in macro build_model_complete_sql (macros/sql_builders.sql)
16:29:39    > called by macro run_test (macros/tests.sql)
16:29:39    > called by macro _test (macros/tests.sql)
16:29:39    > called by macro test (macros/tests.sql)
16:29:39    > called by test mlb_test (tests/mlb_test.sql)
16:29:39    > called by test mlb_test (tests/mlb_test.sql)
```
If I add said line to the test file, it works, but then I get non-mock data:
```
16:30:49  1 of 3 START test mlb_test ..................................................... [RUN]
16:30:49  MODEL: yankees_catchers
16:30:49  TEST:  Test catchers query
16:30:49  Number of Rows do not match! (Expected: 1, Actual: 2)
16:30:49  Rows mismatch:
| diff | name           | team   | position   | height | weight |   age |
| ---- | -------------- | ------ | ---------- | ------ | ------ | ----- |
| +    | "Wil Nieves"   |  "NYY" |  "Catcher" |     71 |    190 | 29.43 |
| +    | "Jorge Posada" |  "NYY" |  "Catcher" |     74 |    205 | 35.54 |
| -    | bobby          | NYY    | Catcher    |     24 |    239 | 23.00 |
16:30:49  1 of 3 FAIL 1 mlb_test ......................................................... [FAIL 1 in 0.06s]
```
I guess I'm doing something wrong, but I'm not quite sure what..
Any thoughts?
Thanks a lot :)

**Comment by cdiniz** [comment]
Hi @amirse. could you please share your model, so we can try to replicate the test?

Also, could you try to change the Mocking Strategy to "Pure" as we mentioned in the README.

You can specify the mocking strategy in the dbt_project.yml file, like this:
```
vars:
  unit_tests_config:
    mocking_strategy: Pure
```
We're rethinking our Mocking Strategies and we're agreeing that we'll make the "Pure" mocking strategy as default mocking strategy, it's the less complex and straightforward to reason.

**Comment by psousa50** [comment]
Hi @amirse, could you also please confirm that you are using `dbt_unit_testing.ref(...)` in your models? if not, you'll need to redefine the 'ref' (and 'source') macros, as explained in the README.

Thanks!

**Comment by acolyer** [comment]
I'm having a very bad case of the same issue. I tried to write a simple test around a mart (that transitively has dependencies on many 10s of other models). Each time I run the test it thinks for a while and then spits out a new (seemingly random) ref from somewhere in that graph that it would like me to add a depends clause for. It's far too time consuming to keep going round this loop, and far too fragile to have every transitive dependency of a model listed explicitly. I'm using the Pure strategy and explicitly using the dbt_unit_testing.ref macro in the definition of the MUT.

**Comment by cdiniz** [comment]
Hi Adrian. Thank you for the feedback.

In your MUT, Are you calling dbt_utils.star or any other macro which receives a 'ref'?

**Comment by acolyer** [comment]
We do have some use of macros that receive refs. Let me try and reduce it down to the simplest model I can create that illustrates the problem and I'll get back to you...

**Comment by psousa50** [comment]
Hi @acolyer, please check the *Known limitations* section on the README of release 0.2.1. to understand how to overcome this issue. Thanks for your feedback 👍

**Comment by acolyer** [comment]
The '-- depends_on: ...' trick does work, but unfortunately it is not practical for us. If it was only the immediate dependencies of the MUT that had to be included this way it would be manageable, but we're finding that every ancestor model needs to be included - and that's a very long list for us. It takes one iteration through a compile cycle to uncover each additional dependency that dbt wants us to explicitly add which is really slow, and moreover we'll end up making a fragile maintenance problem downstream by effectively hard-coding the DAG at the top of each test file. I wonder if, for example, the '--depends_on: ' statements could themselves be generated by the test macros? I had a quick look into that and couldn't get it going last week, but I plan to spend some more time on this problem this week...

**Comment by acolyer** [comment]
For anyone else coming to this in the future, I finally managed to get things working after clearing up a number of my misunderstandings. Here's what I found worked for us:

* Follow the suggestion in the docs to provide a replacement ref macro wrapping dbt_unit_testing.ref. We are introducing testing with dbt_unit_testing to a largish project, and changing all of the refs would be intrusive at this point. I had mistakenly thought I only needed to change refs for models directly referenced from the MUT, but it turned out this isn't the case. Using the wrapper ref makes this all much easier. (And the same thing with the source wrapper).
* Find all the places that you're passing a ref to a macro, and change it to 'builtins.ref' to bypass the wrapper (you can do this incrementally, just try writing tests and dbt will complain if you haven't wrapped a macro call that you should have, saying it was expecting a relation but got a string value instead).
* Just for those models that directly use one of these macros, add the suggested --depends line at the top of your test file

This is so much better than having to have a depends line for every single transitive dependency!

Thanks for all your hard work on the project, we're really excited to be using it!

**Comment by psousa50** [comment]
Hi @acolyer, thank you for your support, your explanation is perfect. We should improve the README with something similar 🙂
