### ISSUE TITLE
SQL Comments throw dbt-unit-testing off

### ISSUE THREAD

**Issue by sbalnojan** [EqualExperts/dbt-unit-testing#79]
Both kinds of SQL comments ("--" as well as "/* */") either in the model or in the test seem to really annoy dbt-unit-testing producing a variety of hard-to-understand errors.

For instance: 
- with /**/ commented out tests are still parsed & produce errors (e.g. missing column "x")
- models with comments tend to produce a "syntax error near line ...." error on running the tests.

Quick fix for now: 
Don't use any comments. Neither in the test nor in the model.

**Comment by psousa50** [comment]
This should have been fixed in release 0.2.0. Thanks for your feedback!
