### ISSUE TITLE
Complexities created with the introduction of new mocking strategies.

### ISSUE THREAD

**Issue by cdiniz** [EqualExperts/dbt-unit-testing#81]
During the last developments, we listened to feedback and introduced a couple of 'mocking strategies' which facilitate the mocking of tables. However, it added underlying complexities and a steeper learning curve to using the framework.
Also, we lost one of our original goals of the framework:

> No dependencies on the underlying database (apart from the ability to run the SQL).

We solved adding another mocking strategy which is the 'pure'.

The added complexities also turned the macros code into a state that needs to be revisited (tech-dept, I mean).

After a few conversations with @psousa50, we've decided to stop new developments on the framework (then the PRs are stable for a while), and we are revisiting the framework's purpose.

Our agreement is: 
- Remove the Mocking Strategies: Bring the original idea back (No dependencies ...) as the default behaviour of the framework, so you need to mock all the required fields for every mock to run.
- Add an option to the mock functions (mock_ref and mock_source) which is include_extra_columns.
```
{% call dbt_unit_testing.mock_ref ('model_a', {"include_extra_columns": true}) %}
```
which will inspect the dependency graph,  it will get the column information from dependent models, and when/if reach the sources it will inspect the database schema. There won't be any schema/source file inspection to grab the columns, it will be all based on the graph, and the DB source definition. 

We think with this solution we have a simpler and more robust framework, and we are giving the option to enrich your mocks with the price depending on the underlying source tables on the database.

We, mostly Pedro, is working on it at branch [remove-mocking-strategy](https://github.com/EqualExperts/dbt-unit-testing/tree/remove-mocking-strategy). This will introduce breaking changes, and then we'll release it under 0.2.1

We're having holidays and busy times, although we'll try to ship this next month.

If you have any feedback we're eager to consider it.

**Comment by psousa50** [comment]
We would like to go back to the basis, as Claudio said, while still being able to tackle these two issues:

- Too complex queries
- Too many database roundtrips

So, by default the framework will keep the queries complexity and the database roundtrips to a minimum as long as the tests obey these two conditions:

- mock all models and sources used by the model being tested
- specify all columns on the mock SQL

This is equivalent to our ‘pure’ strategy, the database will only be used to run the final test query, and this query will be as simple as your model and mocks are.

Now, if you don’t want to mock all the models or don’t want to specify all the columns when mocking, the framework can help you there if you don’t care about some extra calls to the database and a perhaps more complicated final test query.
 
By the way, the include_extra_columns option will be false by default, so you won’t need to specify it in all your models.

We will soon release a new version with this in mind, and it would help a lot if you could test this release in your project and provide some feedback.

Thank you!
