### ISSUE TITLE
Cannot compile test

### ISSUE THREAD

**Issue by minhcanh198** [EqualExperts/dbt-unit-testing#84]
I cloned your repo to my local, then I just use the jaffle_shop folder. But when I compile use `dbt compile` command, it threw the error: 
`Runtime Error
  Compilation Error in test tests_using_include_missing_columns (tests/unit/tests_using_include_missing_columns.sql)
    'None' has no attribute 'startswith'

    > in macro quote_identifier (macros/utils.sql)
    > called by macro build_node_sql (macros/sql_builders.sql)
    > called by macro build_model_complete_sql (macros/sql_builders.sql)
    > called by macro build_node_sql (macros/sql_builders.sql)
    > called by macro enrich_mock_sql_with_missing_columns (macros/mock_builders.sql)
    > called by macro build_mocks_and_expectations (macros/tests.sql)
    > called by macro test (macros/tests.sql)
    > called by macro default__quote_identifier (macros/utils.sql)
    > called by test tests_using_include_missing_columns (tests/unit/tests_using_include_missing_columns.sql)`

How can I solve this? my profiles.yml is:

`jaffle_shop:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{ env_var('MYSQL_HOST') }}"
      port: 3306
      schema: "{{ env_var('MYSQL_DATABASE') }}"
      username: "{{ env_var('MYSQL_USER') }}"
      password: "{{ env_var('MYSQL_PASSWORD') }}"`

**Comment by minhcanh198** [comment]
Can I use this on MYSQL? I now can run on Postgres.

**Comment by psousa50** [comment]
Hi @minhcanh198, the jaffle_shop tests are meant to run on a Postgres database.
You can use MYSQL on a dbt project using the *dbt-mysql* adapter, but bear in mind that this adapter is still experimental [(cf. here)](https://docs.getdbt.com/reference/warehouse-profiles/mysql-profile#:~:text=Overview%20of%20dbt%2Dmysql%E2%80%8B&text=Only%20tested%20with%20dbt%2Dadapter,MariaDB%2010.5)
