### ISSUE TITLE
Cannot compile test

### ISSUE THREAD

**Issue by LiliaBh** [EqualExperts/dbt-unit-testing#87]
Hi,

when my expectation is not met, I receive the correct error code with table mismatched records. However, when everything is correct, I receive the following error: 

```
002022 (42601): SQL compilation error:
16:39:39    Missing column specification
16:39:39    compiled SQL at target/run/dbt_data_transformation/tests/assert_data_normalized.sql
```

any idea where this is coming from? 
The columns of the models I am mocking are defined correctly and options is set to include missing columns.
Version installed is 0.2.2 and dbt-snowflake is 1.2.0.

**Comment by psousa50** [comment]
Hi @LiliaBh, could you please share the compiled SQL at *target/run/dbt_data_transformation/tests/assert_data_normalized.sql*? The model SQL and the test SQL would also help, if you can share that.
Thank you!

**Comment by LiliaBh** [comment]
Hi @psousa50, thank you for the follow up! 

We would like to test that data is correctly selected from table _bookings_raw_ in table _booking_data_.
We perform a join operation in booking_data to _supply_chain_ table adding more information, but in this test, we only want to check that data is moved correctly from  _bookings_raw_ to table _booking_data_. So the following setup returns the behavior I have described previously:

**The Test SQL**

```
-- depends_on: {{ ref('supply_chain'), ref('bookings_raw') }}
{{ config(tags=['unit-test', 'snowflake'], materialized='table') }}
{% set options = {"include_missing_columns": true} %}

{% call dbt_unit_testing.test ('bookings_data','should have all transactions from raw layer') %}
  {% call dbt_unit_testing.mock_ref('bookings_raw', options) %}
     select 'transaction_1'::string as transaction_id,
     'CANCELLED'::string as state
     union all
     select 'transaction_2'::string  as transaction_id,
     'BOOKED'::string as state
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
     select 'transaction_1'::string as transaction_id,
     'CANCELLED'::string as state
     union all
     select 'transaction_2'::string  as transaction_id,
     'BOOKED'::string as state
  {% endcall %}
{% endcall %}

```

**target/run/dbt_data_transformation/tests/assert_data_normalized.sql** 
```
      create or replace transient table TEST_DB.dbt_test__audit.assert_data_normalized  as
      (-- depends_on: ('"supply_chain"', '"bookings_raw"')  
    select 1 from (select 1) as t where False
      );
```

**SQL of the model to be tested bookings_data.sql**
```
    select
        r.transaction_id,
        r.state
    from {{ref('bookings_raw')}} r
    left outer join {{ref('supply_chain')}} sc on (r.transaction_id = sc.transaction_id)
```

**Comment by psousa50** [comment]
Hi @LiliaBh , could you please try the latest release (v0.2.5) and check if it solves this issue?

Thank you!
