### ISSUE TITLE
Pass a CSV file to dbt_unit_testing.mock_ref ? 

### ISSUE THREAD

**Issue by antaradas94** [EqualExperts/dbt-unit-testing#91]
Hi ,
this package is really helpful in checking our SQL Logic. Thanks for it 👍 
We have been using it for testing our basic SQL in our dbt and was wondeing if there is a possibility to use csv/yml files in the dbt_unit_testing.mock_ref ( ) .
This would be really helpful in testing good amount of mock data.
Any leads would be helpful.
Thanks

**Comment by cdiniz** [comment]
Hy @antaradas94, sorry about the delay.
We previously thought about this, but we've decided to take an opinionated way of having the test data inside the test files.
The reason is that it increases the readability and maintainability of the tests.

Thank you for sharing.

**Comment by antaradas94** [comment]
Alright. Thank you for the response.
