### ISSUE TITLE
Snapshot ref throwing invalid identifier error

### ISSUE THREAD

**Issue by shreyaviswanathan** [EqualExperts/dbt-unit-testing#92]
Hello,

I've been working on writing a test for a model that references a snapshot. However, it seems the package seems to run into an error when it comes across the `dbt_valid_from` field in the snapshot. When I removed references to the `dbt_valid_from` field from the code, the error (shown below) resolves.

`000904 (42000): SQL compilation error: error line 29 at position 94
invalid identifier 'COMPANY_SNAPSHOT.DBT_VALID_FROM' `

Any idea why this is happening and how to avoid it?

**Comment by cdiniz** [comment]
Hi @shreyaviswanathan, sorry about the delay.
Have you solved the issue?

Thanks.

**Comment by psousa50** [comment]
Hi @shreyaviswanathan , just wanted to give you a quick update on the issue you raised. It seems that the issue has been inactive for a while now. If you're still facing the problem or have any other issues, please don't hesitate to let us know. We really appreciate your support and hope to work with you again in the future.
