### ISSUE TITLE
How to assert on no rows being returned

### ISSUE THREAD

**Issue by the-serious-programmer** [EqualExperts/dbt-unit-testing#93]
Based on the current documentation and examples it is unclear to me if this is possible and if so, how. 
The ability to do so would help with validating that certain filters work as expected.

**Comment by psousa50** [comment]
That's a very good point! 

I'm afraid it's not supported right now, maybe you could try to add a row to the mocked model that's not filtered out by your filter, and use that row on the expectations.
Meanwhile, we can try to think of a way to support this, maybe something like:

`{% call dbt_unit_testing.expect_no_rows() %}
{% endcall %}
`
What do you think?

**Comment by the-serious-programmer** [comment]
Thanks for your response! I like your suggestion, the only alternative I can imagine is that a `times` parameter gets added to the current expect function that asserts how many times the expectation is expected. 

This way:
- No new function/macro has to be added
- The default value can be 1
- The scenario for this issue is covered, as you could set times to 0
- A potential scenario for expecting a row multiple times can be covered as well, although I am not sure what the implications for that would be. (Would that work out of the box?)
