### ISSUE TITLE
BigQuery - using `_PARTITIONTIME` column leads to `Unrecognized name` error

### ISSUE THREAD

**Issue by jurasan** [EqualExperts/dbt-unit-testing#99]
I have an incremental model, where I need to filer using `_PARTITIONTIME`. 

select * FROM
    {{ dbt_unit_testing.source('source_schema', source_table_1') }}
where _PARTITIONTIME < '2022-11-01'

`dbt run` works, but `dbt test` fails with `Unrecognized name: _PARTITIONTIME at [21:7]`

Is there a way to test models that use _PARTITIONTIME ?

**Comment by cdiniz** [comment]
Hi @jurasan, sorry about the delay in answering.
We didn't have time to look into it.
Have you solved it?

Thank you

**Comment by yoheimiyamoto** [comment]
@jurasan @cdiniz 
I had same situations. #119 
We can not use `{"include_missing_columns": True}` options for tables that require a partition filter. You need to change `{"include_missing_columns": True}` to false.

**Comment by psousa50** [comment]
Hi @jurasan, based on my understanding, it seems like you may want to consider mocking the value of the _PARTITIONTIME column to test the logic effectively. Including _PARTITIONTIME in the mock_ref of your model should help you avoid encountering that error.

Let me know if this helps, I apologize if I am missing something

**Comment by cdiniz** [comment]
Hi there, we are doing a clean-up of old/inactive Issues.
Happy to open again if there is a need for that.
Thank you for collaboration!
